apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    editable: true
    jsonData:
      protocol: "http"
      defaultDatabase: logs
      server: clickhouse
      port: 8123
      username: ""
      password: ""
      tlsSkipVerify: true
      maxOpenConns: 10
    secureJsonData:
      password: ""
