app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-base-url: ${BOT_URL:http://localhost:8081/api/v1}
  include-stacktrace: false

kafka:
  topic:
    updates: updates-topic
    dlq: updates-topic-dlt

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bot-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
