- name: Create users
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    create_home: yes
    groups: sudo
    append: yes
  loop: "{{ users }}"

- name: Set up authorized_keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  loop: "{{ users }}"
